apiVersion: batch/v1
kind: Job
metadata:
  name: flokkr-install-test
spec:
  template:
    spec:
      containers:
      - name: helmjob
        image: flokkr/flokkr-operator
        command: ["",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
