apiVersion: apps/v1
kind: Deployment
metadata:
  name: flokkr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flokkr-operator
  template:
    metadata:
      labels:
        name: flokkr-operator
    spec:
      containers:
        - name: flokkr-operator
          image: quay.io/flokkr/operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - flokkr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "flokkr-operator"
